### ISSUE TITLE
Error in URock Analyzer part2

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#43]
Model runs successfully but the Analyzer complains. I ran at 1 meter resolution. 

[Modeloutput.zip](https://github.com/UMEP-dev/UMEP-processing/files/12883241/Modeloutput.zip)

```
QGIS version: 3.32.3-Lima
QGIS code revision: 67d46100b5
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0

PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)
Algorithm started at: 2023-10-12T13:58:36
Algorithm 'Urban Wind Field: URock AnalyZer' starting…
Input parameters:
{ 'ID_FIELD_LINES' : 'id', 'ID_FIELD_POLYGONS' : '', 'INPUT_LINES' : 'C:/Users/xlinfr/Downloads/dataWindExerciseTEst/lineprofile.shp', 'INPUT_POLYGONS' : None, 'INPUT_WIND_FILE' : 'C:\\Users\\xlinfr\\Downloads\\dataWindExerciseTEst\\out270_1m_1mout\\urock_output.nc', 'IS_STREAM' : False, 'OUTPUT_DIRECTORY' : 'C:\\Users\\xlinfr\\Downloads\\dataWindExerciseTEst\\out270_1m_1mout', 'SIMULATION_NAME' : '' }

Load NetCDF file in Python and save as csv file...
Load csv file into H2GIS Database...
Calculates vertical sectional plot (along lines)...
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Chunk 1120 not found [1.4.200/9]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "JdbcPreparedStatement.java", line 237, in org.h2.jdbc.JdbcPreparedStatement.execute
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Unable to read the page at position 307863261765461 [1.4.200/6]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "JdbcPreparedStatement.java", line 237, in org.h2.jdbc.JdbcPreparedStatement.execute
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
org.h2.jdbc.org.h2.jdbc.JdbcSQLNonTransientException: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Unable to read the page at position 307863261765461 [1.4.200/6]"; SQL statement:

CREATE SPATIAL INDEX IF NOT EXISTS id_THE_GEOM_ALL_POINTS_20231012135836 ON ALL_POINTS_20231012135836(THE_GEOM); [50000-200]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\postprocessor\urock_analyser_algorithm.py", line 275, in processAlgorithm
plotSectionalViews(pluginDirectory = plugin_directory,
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\urock_analyser_functions.py", line 208, in plotSectionalViews
cursor.execute("""
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 536, in execute
_handle_sql_exception()
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 165, in _handle_sql_exception_jpype
reraise(exc_type, exc_info[1], exc_info[2])
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 57, in reraise
raise value.with_traceback(tb)
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
jaydebeapi.DatabaseError: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Unable to read the page at position 307863261765461 [1.4.200/6]"; SQL statement:

CREATE SPATIAL INDEX IF NOT EXISTS id_THE_GEOM_ALL_POINTS_20231012135836 ON ALL_POINTS_20231012135836(THE_GEOM); [50000-200]

Execution failed after 796.75 seconds (13 minutes 17 seconds)

Loading resulting layers
Algorithm 'Urban Wind Field: URock AnalyZer' finished
```

**Comment by j3r3m1** [comment]
Works for me, I cannot reproduce your error (see update in your other issue #41).

I suppose a problem with Java stopping during the calculation or something like that. Can you retry to analyse ?

**Comment by j3r3m1** [comment]
I have an older version of OpenJDK. I will have a try with version 21
