### ISSUE TITLE
Error when install Python Packages for UMEP

### ISSUE THREAD

**Issue by evbla** [UMEP-dev/UMEP-processing#48]
**Hej!**

**When launching UMEP for processing, it requires the download of new Python packages. Once this is completed, the following error message occurs:**

AttributeError: module 'numpy' has no attribute 'long' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/beam0/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 46, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/beam0/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/beam0/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 54, in 
    from .processor.urock_processing_algorithm import URockAlgorithm
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/beam0/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 64, in 
    from ..functions.URock import MainCalculation
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/beam0/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\MainCalculation.py", line 19, in 
    from . import WindSolver
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/beam0/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\WindSolver.py", line 18, in 
    from numba import jit
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numba\__init__.py", line 18, in 
    from numba.core import types, errors
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numba\core\types\__init__.py", line 108, in 
    long_ = _make_signed(np.long)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'

**When I choose to cancel the installation of new Python packages, the same message reappears.**

**Regards, 
Evelina**

**Comment by biglimp** [comment]
Evelina, write the following code in your QGIS Python console and report the result. @j3r3m1 , do you have any ideas on how to solve this? I know Evelina have another Python installation (3.11) on her computer also.

```
import numpy
numpy.__version__

import numba
numba.__version__

```

**Comment by evbla** [comment]
**Numpy version:**
1.24.1

**Numba version:** 

Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numba\__init__.py", line 18, in <module>
    from numba.core import types, errors
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numba\core\types\__init__.py", line 108, in <module>
    long_ = _make_signed(np.long)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'

**Does some of the versions of numpy not support numba?**

**Comment by evbla** [comment]
I changed the numpy version to 1.23.3 and it works now! I think it is good to specify the type of numba library used.

**Comment by j3r3m1** [comment]
What is the numba version you are using ? Can you check using pip list and checking the version associated to numba ?

Here are the numba versions and the corresponding numpy dependency: https://numba.readthedocs.io/en/stable/user/installing.html#version-support-information

I do not really know why the numba version installed is not directly the right one (associated to the numpy dependency). Is it the first time you install UMEP ? If yes it might be that we do not check that the numba version installed works for the installed numpy version.
Should we add a way to check that

**Comment by evbla** [comment]
I am using numba version 0.56.4. And no it is not the first time using UMEP.

**Comment by j3r3m1** [comment]
Do you remember when was the last time you updated the UMEP-processing plugin ? I suppose the problem comes from the fact that your numpy version was updated (outside UMEP update) but that the last update you made of UMEP created the version conflict...

**Comment by biglimp** [comment]
As this seems solved, I will close this.
