### ISSUE TITLE
UMEP for Processing not installing on QGIS 3.22

### ISSUE THREAD

**Issue by Cas6713** [UMEP-dev/UMEP-processing#65]
UMEP for Processing is not installing saying it is missing python dependencies. However, I definitely have python installed (3.9+) and I use it with VSCode. I am unable to understand this error - please help. I do not understand how to add these myself.

Couldn't load plugin 'processing_umep' due to an error when calling its classFactory() method 

SystemExit: 'jaydebeapi' Python package is missing 
Traceback (most recent call last):
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\H2gisConnection.py", line 23, in 
    import jaydebeapi
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'jaydebeapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 46, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 54, in 
    from .processor.urock_processing_algorithm import URockAlgorithm
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 64, in 
    from ..functions.URock import MainCalculation
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\MainCalculation.py", line 11, in 
    from . import H2gisConnection
  File "C:\PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\H2gisConnection.py", line 27, in 
    exit("'jaydebeapi' Python package is missing")
  File "C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 'jaydebeapi' Python package is missing

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.9-Białowieża Białowieża, a8e9e6fa 

Python Path:
C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages
C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages
C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python
C:/Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python/plugins
C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python
C:\Program Files\QGIS 3.22.9\bin\python39.zip
C:\PROGRA~1\QGIS32~1.9\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib
C:\Program Files\QGIS 3.22.9\bin
C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.9\apps\Python39
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages\Pythonwin
C:/Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by biglimp** [comment]
Your version of QGIS is way too old. Update to a newer version (<3.28) and try again.

**Comment by Cas6713** [comment]
@j3r3m1 hi, yes it works with QGIS 3.34! Thanks!
