### ISSUE TITLE
Memory issue in SUEWS

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#86]
Running the [tutorial using NY-data](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html#suewsspatial) within a QGIS session (3.38.2) on Windows 11 with 16Gb memory. 16 grids and one year of hourly data. This was no problems before. Have something changed in SuPy creating this issue?

```
Traceback (most recent call last):
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\suews_algorithm.py", line 250, in processAlgorithm
df_output, df_state_final = sp.run_supy(df_forcing,
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\xlinfr\AppData\Roaming\Python\Python312\site-packages\supy\_supy_module.py", line 371, in run_supy
df_output, df_state_final = run_supy_ser(
^^^^^^^^^^^^^
File "C:\Users\xlinfr\AppData\Roaming\Python\Python312\site-packages\supy\_run.py", line 415, in run_supy_ser
df_output = df_output.drop("ESTM", axis=1, level="group")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\frame.py", line 5581, in drop
return super().drop(
^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\generic.py", line 4788, in drop
obj = obj._drop_axis(labels, axis, level=level, errors=errors)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\generic.py", line 4869, in _drop_axis
new_mgr = self._mgr.reindex_indexer(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\internals\managers.py", line 680, in reindex_indexer
new_blocks = self._slice_take_blocks_ax0(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\internals\managers.py", line 843, in _slice_take_blocks_ax0
nb = blk.take_nd(taker, axis=0, new_mgr_locs=mgr_locs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\internals\blocks.py", line 1307, in take_nd
new_values = algos.take_nd(
^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\array_algos\take.py", line 117, in take_nd
return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\array_algos\take.py", line 157, in _take_nd_ndarray
out = np.empty(out_shape, dtype=dtype)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 11.7 GiB for an array with shape (936, 1681920) and data type float64

Execution failed after 744.44 seconds (12 minutes 24 seconds)
```

**Comment by sunt05** [comment]
That's odd - if this case used to run smoothly, there might be an issue with how NumPy clears arrays. Have you recently upgraded to NumPy version 2?

One workaround could be reducing the number of spatial grids from 16 to 8, then concatenating the separate results (`df_output`s) afterwards.

**Comment by biglimp** [comment]
IT was the human factor. I tried to do too many things at the same time with my PC. Closing.
