### ISSUE TITLE
Test based on Tutorial -- copying or increasing the size of the planting_area.shp -- Attribute Error

### ISSUE THREAD

**Issue by rarygit** [UMEP-dev/UMEP-processing#9]
Hi Nils, 

Now I am experimenting/testing using the Tutorial dataset for TreePlanter.

Keeping everything else the same as in the Tutorial, including the output from SOLWEIG, I tested 
(1) exported the planting_area.shp to a new file, planting_area_copy.shp
(2) enlarged the planting_area.shp and saved file as "planting_area2.shp" 

As attached in two zip files.

[planting_area_copy.zip](https://github.com/UMEP-dev/UMEP-processing/files/6570504/planting_area_copy.zip)
[planting_area2.zip](https://github.com/UMEP-dev/UMEP-processing/files/6570416/planting_area2.zip)

In both cases, TreePlanter simulation failed with error:  AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

The planting_area.shp is not required in the steps prior to using the TreePlanter function.

What has TreePlanter reacted to in both the exported and enlarged shapefile?

#################################################################################

Failed:
(1) Exported the original shapefile "planting_area.shp" . Exactly same error for enlarging the original shapefile.

Processing algorithm…
Algorithm 'Outdoor Thermal Comfort: TreePlanter' starting…
Input parameters:
{ 'DIA' : 5, 'END_HOUR' : 15, 'GREEDY_ALGORITHM' : False, 'HEIGHT' : 10, 'INCLUDE_OUTSIDE' : True, 'INPUT_POLYGONLAYER' : '/media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/planting_area_copy.shp|layername=planting_area_copy', 'ITERATIONS' : 2000, 'NTREE' : 3, 'OUTPUT_CDSM' : 'TEMPORARY_OUTPUT', 'OUTPUT_POINTFILE' : 'TEMPORARY_OUTPUT', 'RANDOM_STARTING' : False, 'SOLWEIG_DIR' : '/media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3', 'START_HOUR' : 13, 'TRANS_VEG' : 3, 'TRUNK' : 3, 'TTYPE' : 0 }

Initializing and loading layers...
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Shadow_1983_173_1300D.tif..
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Tmrt_1983_173_1300D.tif..
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Shadow_1983_173_1400D.tif..
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Tmrt_1983_173_1400D.tif..
Traceback (most recent call last):
File "/home/l1nux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP-processing-main/processor/treeplanter_algorithm.py", line 277, in processAlgorithm
tree_input = Inputdata(r_range, sh_fl, tmrt_fl, infolder, inputPolygonlayer, feedback)
File "/home/l1nux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP-processing-main/functions/TreePlanter/TreePlanter/TreePlanterClasses.py", line 95, in __init__
self.selected_area = dataSetSel.ReadAsArray().astype(np.float)
AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

Execution failed after 0.04 seconds

###########################################################################

Successful
(2) TreePlanter simulation using original shapefile "planting_area.shp"

Loading resulting layers
Algorithm 'Outdoor Thermal Comfort: TreePlanter' finished
QGIS version: 3.16.4-Hannover
Qt version: 5.12.9
GDAL version: 3.2.1
GEOS version: 3.9.0-CAPI-1.14.1
PROJ version: Rel. 7.2.0, November 1st, 2020
Processing algorithm…
Algorithm 'Outdoor Thermal Comfort: TreePlanter' starting…
Input parameters:
{ 'DIA' : 5, 'END_HOUR' : 15, 'GREEDY_ALGORITHM' : False, 'HEIGHT' : 10, 'INCLUDE_OUTSIDE' : True, 'INPUT_POLYGONLAYER' : '/media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/planting_area.shp', 'ITERATIONS' : 2000, 'NTREE' : 3, 'OUTPUT_CDSM' : 'TEMPORARY_OUTPUT', 'OUTPUT_POINTFILE' : 'TEMPORARY_OUTPUT', 'RANDOM_STARTING' : False, 'SOLWEIG_DIR' : '/media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3', 'START_HOUR' : 13, 'TRANS_VEG' : 3, 'TRUNK' : 3, 'TTYPE' : 0 }

Initializing and loading layers...
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Shadow_1983_173_1300D.tif..
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Tmrt_1983_173_1300D.tif..
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Shadow_1983_173_1400D.tif..
Loading /media/l1nux/SAN240/SIM/WIP_UMEP/TreePlantTut/TreePlanterTestData/SOLWEIG_OUT3/Tmrt_1983_173_1400D.tif..
Running hill climbing algorithm with genetic algorithm for starting positions...
1600 possible locations for trees...
10.0 percent of iterations finished...
20.0 percent of iterations finished...
30.0 percent of iterations finished...
40.0 percent of iterations finished...
50.0 percent of iterations finished...
60.0 percent of iterations finished...
70.0 percent of iterations finished...
80.0 percent of iterations finished...
90.0 percent of iterations finished...
TreePlanter: Model calculation finished.
Execution completed in 66.62 seconds
Results:
{'OUTPUT_CDSM': '/tmp/processing_GZvFZC/d8b6b51868bc49aea9de6d1721dabbcd/OUTPUT_CDSM.tif',
'OUTPUT_POINTFILE': '/tmp/processing_GZvFZC/68b56c99ee89410a99f143c17acefb71/OUTPUT_POINTFILE.gpkg'}

Loading resulting layers
Algorithm 'Outdoor Thermal Comfort: TreePlanter' finished

**Comment by rarygit** [comment]
I ran another simulation with TreePlanter using a new plant area polygon.
Finished OK, no problems.

I think the issue that I have described above is not significant and probably due to own error with not re-running SOLWEIG 
So this issue can be closed.
