### ISSUE TITLE
Error in wind solver in URock

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#92]
We get an error, both trying with and without vegetation. We have the latest version from GH. @j3r3m1 , can you see what is wrong? I attach the data.

[urock_error.zip](https://github.com/user-attachments/files/17934087/urock_error.zip)

Fredrik and Nils

```
QGIS version: 3.40.1-Bratislava
QGIS code revision: 989853a7
Qt version: 5.15.13
Python version: 3.12.7
GDAL version: 3.9.3
GEOS version: 3.13.0-CAPI-1.19.0
PROJ version: Rel. 9.5.0, September 15th, 2024
PDAL version: 2.8.1 (git-version: a06325)
Algorithm started at: 2024-11-27T13:13:06
Algorithm 'Urban Wind Field: URock v2023a' starting…
Input parameters:
{ 'ATTENUATION_FIELD' : '', 'BUILDINGS' : 'D:/GRUPAS/THERMAL_COMFORT_FIVE_CITIES/MALMO/UROCK/UROCKIN/build_urock.shp', 'HEIGHT_FIELD_BUILD' : 'ROOF_H', 'HORIZONTAL_RESOLUTION' : 4, 'INPUT_PROFILE_FILE' : '', 'INPUT_PROFILE_TYPE' : 0, 'INPUT_WIND_DIRECTION' : 230, 'INPUT_WIND_HEIGHT' : 10, 'INPUT_WIND_SPEED' : 2, 'LOAD_OUTPUT' : True, 'OUTPUT_FILENAME' : 'urock_output', 'RASTER_OUTPUT' : 'D:/GRUPAS/THERMAL_COMFORT_FIVE_CITIES/MALMO/UROCK/UROCKIN/temp_ClippedDSM.tif', 'SAVE_NETCDF' : False, 'SAVE_RASTER' : True, 'SAVE_VECTOR' : False, 'UROCK_OUTPUT' : 'C:\\Users\\xlinfr\\Desktop', 'VEGETATION' : None, 'VEGETATION_CROWN_BASE_HEIGHT' : '', 'VEGETATION_CROWN_TOP_HEIGHT' : '', 'VERTICAL_RESOLUTION' : 4, 'WIND_HEIGHT' : '1.5' }

Writing settings for this model run to specified output folder (Filename: RunInfoURock_YYYY_DOY_HHMM.txt)
Initiating algorithm
Creates an H2GIS Instance and load data
Creates the stacked blocks used as obstacles
Rotates obstacles to the right direction and calculates geometry properties
Roughness zone properties are:

- z0: 0.28455975325252314
- d: 0.9747694678387907
- Hr: 4.722473400400691
- H_ob_max: 14.0
- lambda_f: 0.060256507369290606
Creates the 2D Röckle zones
Creates the 2D grid
Initializes the 3D grid within Röckle zones
Deals with building zones superimposition
Deals with vegetation zones superimposition
Initialize the 3D wind in the grid
Rasterize the data
Apply the wind solver equations
Iteration 1 (max 500) - eps = 0.677201 >= 0.0001

Iteration 51 (max 500) - eps = 0.150132 >= 0.0001

Iteration 101 (max 500) - eps = 0.053512 >= 0.0001

Iteration 151 (max 500) - eps = 0.018887 >= 0.0001

Iteration 201 (max 500) - eps = 0.006393 >= 0.0001

Iteration 251 (max 500) - eps = 0.002029 >= 0.0001

Iteration 301 (max 500) - eps = 0.00062 >= 0.0001

Iteration 351 (max 500) - eps = 0.000187 >= 0.0001

Traceback (most recent call last):
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 447, in processAlgorithm
MainCalculation.main(javaEnvironmentPath = javaEnvVar,
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\MainCalculation.py", line 811, in main
saveData.saveBasicOutputs(cursor = cursor , z_out = z_out,
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\saveData.py", line 163, in saveBasicOutputs
srid = srid)
^^^^
UnboundLocalError: cannot access local variable 'srid' where it is not associated with a value

Execution failed after 23.20 seconds

Loading resulting layers
Algorithm 'Urban Wind Field: URock v2023a' finished
```

**Comment by j3r3m1** [comment]
Good catch ! I have never tried removing the netCDF saving... under tested so far. Now works also in this case (download new version - 2.1.1 wow what a change in the 2.1 !!)
