### ISSUE TITLE
New memory issue without vegetation

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#94]
Here is another memory issue. I suspect that it might be cos of complex geometries, or what do you think? I attach the data.

[temp_ClippedDSM.zip](https://github.com/user-attachments/files/18005325/temp_ClippedDSM.zip)

```
Connecting to database
        ->C:\Users\xlinfr\AppData\Local\Temp\myDbH21733259702_6765358
C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\functions\URock\h2gis-standalone\h2gis-dist
Connected!

Spatial functions added!

Load input data
Load table 'build_pre_srid_20241203220142'
Creates blocks and stacked blocks
Rotates geometries from 230.0 degrees
Identify block base height and block cavity base
Calculates obstacle properties
Calculates zone properties
Initializes upwind facades
Update upwind facades base height
Initializes downwind facades

Calculates study area properties
Rotates geometries from -230.0 degrees
Creates displacement zones
Creates cavity and wake zones
Creates street canyon zones
Creates rooftop zones (perpendicular and corner)
Creates built-up and open vegetation zones
Identify the buildings concerned by the impacted zone chosen by the user
Creates the grid of points
Affects each grid point to a building Rockle zone and calculates needed 
          variables for 3D wind speed
Affects each grid point to a vegetation Rockle zone and calculates 
          needed variables for 3D wind speed
Remove some of the Röckle zone points
Creates backward zones
Calculates the 3D wind speed factor value for each point of each BUILDING zone
Calculates the 3D wind speed factor value for each point of each VEGETATION zone
Deals with superimposition (keeps only 1 value per 3D point)
Deals with superimposition (keeps only 1 value per 3D point)
Identify upstreamer points in TEMPO_WEIGHTING table
Identify upstreamer points in TEMPO_PRIORITIES table
Identify upstreamer points in TEMPO_PRIORITIES_WEIGHT table
Deals with superimposition (keeps only 1 value per 3D point)
Identify upstreamer points in TEMPO_WEIGHTING table
Identify upstreamer points in TEMPO_PRIORITIES table
Identify upstreamer points in TEMPO_PRIORITIES_WEIGHT table
Identify grid points intersecting buildings
Set the initial 3D wind speed field
Logged critical: Traceback (most recent call last):
  File "C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\processor\urock_processing_algorith
    MainCalculation.main(javaEnvironmentPath = javaEnvVar,
  File "C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\functions\URock\MainCalculation.py"
    InitWindField.setInitialWindField(cursor = cursor,
  File "C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\functions\URock\InitWindField.py", 
    V: [val for j in range(nPoints[Y])
        ^^^
MemoryError
    processing.run("umep:Urban Wind Field: URock", parin)
  File "C:\OSGeo4W\apps\qgis\python\plugins\processing\tools\general.py", line 93, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\qgis\python\plugins\processing\core\Processing.py", line 192, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\qgis\python\plugins\processing\gui\AlgorithmExecutor.py", line 70, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_core.QgsProcessingException: Traceback (most recent call last):
  File "C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\processor\urock_processing_algorithm.py", line 447, in processAlgorithm
    MainCalculation.main(javaEnvironmentPath = javaEnvVar,
  File "C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\functions\URock\MainCalculation.py", line 635, in main
    InitWindField.setInitialWindField(cursor = cursor,
  File "C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\functions\URock\InitWindField.py", 
line 3050, in setInitialWindField
    V: [val for j in range(nPoints[Y])
        ^^^
MemoryError
```

Here is the settings used:
```
{ 'ATTENUATION_FIELD' : '', 
                'BUILDINGS' : buildname, 
                'HEIGHT_FIELD_BUILD' : 'ROOF_H', 
                'HORIZONTAL_RESOLUTION' : 4, 
                'INPUT_PROFILE_FILE' : '', 
                'INPUT_PROFILE_TYPE' : 0, 
                'INPUT_WIND_DIRECTION' : 230, 
                'INPUT_WIND_HEIGHT' : 10, 
                'INPUT_WIND_SPEED' : 2, 
                'LOAD_OUTPUT' : False, 
                'OUTPUT_FILENAME' : 'ws_1_5magl_' + str(gridid), 
                'RASTER_OUTPUT' : filepath_tempdsm, 
                'SAVE_NETCDF' : False, 
                'SAVE_RASTER' : True, 
                'SAVE_VECTOR' : False, 
                'UROCK_OUTPUT' : output_dir_urock, 
                'VEGETATION' : '', # vegname, 
                'VEGETATION_CROWN_BASE_HEIGHT' : '', 
                'VEGETATION_CROWN_TOP_HEIGHT' : '', #'VEG_H', 
                'VERTICAL_RESOLUTION' : 4, 
                'WIND_HEIGHT' : '1.5' }
```

**Comment by j3r3m1** [comment]
I suspect this is the same issue than #93 but I will check. Can you share the entire data ? There is only the DSM in the issue

**Comment by biglimp** [comment]
Ops. Here are the buildings.

[buildclip393.zip](https://github.com/user-attachments/files/18019296/buildclip393.zip)

**Comment by biglimp** [comment]
Just an update on this one. As the memory issue was different on this one compared to #93 (here RAM memory issue, whereas in #93 we had disk memory issue), I tried to first simplify geometries and then also remove a shimney. However the error is still there. I attach the updated building file if you want to have a look.

[build_urock393_v2.zip](https://github.com/user-attachments/files/18035166/build_urock393_v2.zip)

**Comment by j3r3m1** [comment]
should now be solved with last version. Please try and report

**Comment by biglimp** [comment]
Great now it works! Saw some strange things regarding vegetation. Opening a new isuue.
